/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.vista;

import java.awt.event.ActionListener;

/**
 *
 * @author Healer
 */
public class FRMVentanaInicial extends javax.swing.JFrame {

    /**
     * Creates new form FRMVentanaInicial
     */
    public FRMVentanaInicial() {
        initComponents();
    }
    
    public void escucharBoton(ActionListener manejador){
        this.jbAceptar.addActionListener(manejador);
        this.jbExit.addActionListener(manejador);
        this.jcOpciones.addActionListener(manejador);
    }
    public String devolverCombo() {
        return jcOpciones.getSelectedItem().toString();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fondo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jcOpciones = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        CuadradoAzulInfo = new javax.swing.JLabel();
        jbExit = new javax.swing.JButton();
        jbAceptar = new javax.swing.JButton();
        Logo = new javax.swing.JLabel();
        CuadradoBlanco = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        CuadradoAzul = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Fondo.setBackground(new java.awt.Color(204, 204, 204));
        Fondo.setPreferredSize(new java.awt.Dimension(1280, 720));
        Fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Air Commerce.png"))); // NOI18N
        Fondo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, -1, -1));

        jcOpciones.setBackground(new java.awt.Color(153, 153, 153));
        jcOpciones.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jcOpciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Comprar Vuelos", "Registro y administracion de vuelos" }));
        Fondo.add(jcOpciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 270, 360, 50));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Ingrese una opcion para el metodo de ingreso.png"))); // NOI18N
        Fondo.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 190, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/7740303_summer_plane_airplane_aircraft_flight_icon.png"))); // NOI18N
        Fondo.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, -1, -1));

        CuadradoAzulInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/RectanguloAzulLogin.png"))); // NOI18N
        Fondo.add(CuadradoAzulInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, -1, -1));

        jbExit.setBackground(new java.awt.Color(153, 153, 153));
        jbExit.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jbExit.setText("Salir");
        Fondo.add(jbExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 470, 390, 60));

        jbAceptar.setBackground(new java.awt.Color(51, 51, 255));
        jbAceptar.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jbAceptar.setText("Aceptar");
        Fondo.add(jbAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 390, 390, 60));

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/logo 1.png"))); // NOI18N
        Fondo.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 130, 140, -1));

        CuadradoBlanco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Rectanguloblancologin.png"))); // NOI18N
        Fondo.add(CuadradoBlanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, -10, -1, 730));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Rectanguloblancologin.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        Fondo.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, -1, -1));

        CuadradoAzul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/RectanguloAzulLogin.png"))); // NOI18N
        Fondo.add(CuadradoAzul, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 110, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CuadradoAzul;
    private javax.swing.JLabel CuadradoAzulInfo;
    private javax.swing.JLabel CuadradoBlanco;
    private javax.swing.JPanel Fondo;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton jbAceptar;
    private javax.swing.JButton jbExit;
    private javax.swing.JComboBox<String> jcOpciones;
    // End of variables declaration//GEN-END:variables
}
